#!/bin/sh

rm request_output.txt
rm status_code_output.txt

curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt &
curl -s --location 'localhost:5050/musics' -o request_output.txt -w "%{http_code}\n" >> status_code_output.txt
